[package]
name = "axum"
version = "0.1.0"
edition = "2021"

[dependencies]
ts-rpc = { path = "../..", features = ["axum"] }
axum = "0.6"
serde = { version = "1.0", features = ["derive"] }
tower-http = { version = "0.4", features = ["cors"] }
tokio = { version = "1.0", features = ["full"] }